language: "ko-KR" # 한국말로 설정
early_access: false
reviews:
  profile: "chill" # 리뷰 너무 빡세게는 안한다는 뜻
  request_changes_workflow: true # 코드래빗이 리뷰 끝나면 알아서 PR 승인하게끔
  high_level_summary: true
  poem: true 
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  # 추가 옵션들:
  # path_filters:
  #   - "!**/*.test.ts" # 테스트 파일은 리뷰하지 않음
  #   - "!**/*.spec.ts"
  # knowledge_base:
  #   learnings:
  #     enabled: true # 프로젝트 학습 기능
  # tools:
  #   eslint:
  #     enabled: true
  #   ruff:
  #     enabled: false
chat:
  auto_reply: true
